### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by richwklein** [richwklein/git-cleanup#9]
Tag a release with each merge of a pull request. Example below

```yaml
name: Tag Release on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  tag_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next version
        id: bump_version
        run: |
          if [[ -z "$latest_tag" ]]; then
            new_version="v1.0.0"
          else
            IFS='.' read -r -a parts <<< "${latest_tag//v/}"
            major="${parts[0]}"
            minor="${parts[1]}"
            patch="${parts[2]}"
            new_version="v$major.$minor.$((patch + 1))"
          fi
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "Next release: $new_version"

      - name: Create Git tag
        run: |
          git tag $new_version
          git push origin $new_version

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.new_version }}
          name: Release ${{ env.new_version }}
          draft: false
          prerelease: false
          body: "Automated release for PR #${{ github.event.pull_request.number }} merged by ${{ github.event.pull_request.user.login }}."
```
